logging:
  base_folder: 'demo/optimization/'
  run: 'fit_buddi_flickrci3ds_demo'
  checkpoint_folder: '' 
  validation_folder: ''
datasets:
  train_names: ['demo']
  train_composition: [1.0]
  val_names: []
  demo:
    original_data_folder: 'demo/data/FlickrCI3D_Signatures/demo'
    image_folder: 'images'
  flickrci3ds:
    processed_data_folder: 'datasets/processed/FlickrCI3D_Signatures'
    openpose_folder: 'keypoints/openpose'
    vitpose_folder: 'keypoints/vitpose'
    vitposeplus_folder: 'keypoints/vitposeplus'
    vitdet_folder: 'keypoints/vitdet'
    pseudogt_folder: '' #'hhcs_opti/release_20230811' # we're creating the pseudo ground-truth here, so doesn't exit yet
  chi3d:
    load_contact_frame_only: True
    load_single_camera: False
  augmentation:
    use: False
  processing:
    use: False
model:
  optimization:
    type: 'hhcs'
    print_loss: True
    use_diffusion: True
    use_gt_contact_map: False
    pretrained_diffusion_model_cfg: 'essentials/buddi/buddi_cond_bev_checkpoint_config.yaml'
    pretrained_diffusion_model_ckpt: 'essentials/buddi/buddi_cond_bev_checkpoint.pt'
    sds_type: 'fixed' # fixed, range or adaptive selection of noise level in SDS
    sds_t_fixed: 10
    sds_t_range: [25, 75]
    sds_t_adaptive_i: [1.0, 0.8, 0.6, 0.4, 0.2]
    sds_t_adaptive_t: [100, 80, 60, 40, 20]    
    hhcs:
      max_iters: [100, 100]
      num_prev_steps: 20
      slope_tol: -0.0001
    optimizer: 
      type: 'adam'
      adam:
        lr: 0.01
    losses:
      keypoint2d: # 2d keypoint loss 
        type: 'l2'
        squared: True
        weighted: True
        weight: [0.02, 0.02]
      hhc_contact: # sum over minimum distance between regions in contact
        type: 'hhcmap'
        r2r_dist_type: 'min'
        weight: [0.0, 0.0]
      hhc_contact_general: # contact loss that resolves intersection and brings part close to each other in contact. Memory intense.
        type: 'hhcgen'
        weight: [0.0, 10.0] # must be set to 0.0, because loss is not implemented
      init_pose: # penalize deviation from inital bev pose
        type: 'l2'
        squared: True
        d1_aggregation: 'none'
        weight: [200.0, 200.0]
      pose_prior: # usual gmm pose prior
        type: 'gmm'
        weight: [0.0, 0.0]
      shape_prior: # usual shape prior
        type: 'l2'
        squared: True
        weight: [0.0, 0.0]
      ground_plane:
        type: 'l2'
        squared: True
        d1_aggregation: 'none'
        weight: [0.0, 0.0]
      diffusion_prior_orient: # sds loss
        type: 'l2'
        weight: [0.0, 0.0]
      diffusion_prior_pose: # sds loss
        type: 'l2'
        weight: [100.0, 100.0]
      diffusion_prior_shape: # sds loss
        type: 'l2'
        weight: [10.0, 0.0]
      diffusion_prior_scale: # sds loss
        type: 'l2'
        weight: [0.0, 0.0]
      diffusion_prior_transl: # sds loss
        type: 'l2'
        weight: [10000.0, 10000.0]      
body_model:
  type: 'smplx'
  smplx:
    init:
      batch_size: 1
      gender: 'neutral'
      age: 'kid'
      joint_mapper:
        use: True
        type: 'smpl_to_openpose'
        smpl_to_openpose:
          use_hands: False
          use_face: False
camera:
  type: 'perspective'
  perspective:
    afov_horizontal: 60 # inital angular field of view compatible with bev output
    roll: 180 # inital camera roll compatible with bev output
