logging:
  base_folder: 'outdebug/optimization'
  run: 'demo_flickrsc3ds_pgt'
  checkpoint_folder: '' 
  validation_folder: ''
datasets:
  train_names: []
  train_composition: []
  val_names: ['demo']
  demo:
    original_data_folder: 'datasets/original/moyo_cam05_centerframe/test/'
    bev_folder: 'hmr2'
    openpose_folder: 'openpose'
    vitpose_folder: 'vitpose'
    humans_per_example: 1
    # Use best_match_with_bev_box
    best_match_with_bev_box: True
    unique_keypoint_match: False
      # custom_losses_path: 'moyo_trainval_llava/programs_from_prompt4.json'
    custom_losses_path: 'moyo_test_llava/programs_from_prompt4.json'
      # custom_losses_path: 'datasets/original/moyo_cam05_centerframe/trainval/trainval_gpt4v_custom_losses.json'
      # custom_losses_path: 'datasets/original/moyo_cam05_centerframe/test/test_gpt4v_custom_losses.json'
  chi3d:
    load_contact_frame_only: True
    load_single_camera: False
  augmentation:
    use: False
  processing:
    use: False
model:
  optimization:
    type: 'hhcs'
    print_loss: False
    optimize_camera_trans: False
    hhcs:
      max_iters: [1000, 1000]
      num_prev_steps: 20
      slope_tol: -0.0001
    optimizer: 
      type: 'adam'
      adam:
        lr: 0.01
    losses:
      keypoint2d: # 2d keypoint loss 
        type: 'l2'
        squared: True
        weighted: True
        weight: [0.04, 0.1]
      custom: # sum over minimum distance between regions in contact
        weight: [10000.0, 10000.0]
      hhc_contact_general: # contact loss that resolves intersection and brings part close to each other in contact. Memory intense.
        type: 'hhcgen'
        weight: [0.0, 1000.0] # must be set to 0.0, because loss is not implemented
      init_pose: # penalize deviation from inital bev pose
        type: 'l2'
        squared: True
        d1_aggregation: 'none'
          # weight: [200.0, 200.0]
        weight: [400.0, 400.0]
      pose_prior: # usual gmm pose prior
        type: 'gmm'
        weight: [0.0, 0.0]
      shape_prior: # usual shape prior
        type: 'l2'
        squared: True
        weight: [40.0, 0.0]
      ground_plane:
        type: 'l2'
        squared: True
        d1_aggregation: 'none'
        weight: [0.0, 0.0]
body_model:
  type: 'smplx'
  smplx:
    init:
      batch_size: 1
      gender: 'neutral'
      age: 'kid'
      joint_mapper:
        use: True
        type: 'smpl_to_openpose'
        smpl_to_openpose:
          use_hands: False
          use_face: False
          use_face_contour: False
camera:
  type: 'perspective'
  perspective:
    afov_horizontal: 60 # inital angular field of view compatible with bev output
    roll: 180 # inital camera roll compatible with bev output
