logging:
  base_folder: 'demo/optimization'
  run: 'gpt4v_tables_custom1'
  checkpoint_folder: '' 
  validation_folder: ''
datasets:
  train_names: []
  train_composition: []
  val_names: ['flickrci3ds']
  flickrci3ds:
    processed_data_folder: 'datasets/processed/FlickrCI3D_Signatures'
    openpose_folder: 'keypoints/openpose'
    vitpose_folder: 'keypoints/vitpose'
    vitposeplus_folder: 'keypoints/vitposeplus'
    vitdet_folder: 'keypoints/vitdet'
    pseudogt_folder: '' #'hhcs_opti/release_20230811' # we're creating the pseudo ground-truth here, so doesn't exit yet
    custom_losses_path: 'datasets/original/FlickrCI3D_Signatures/train/val_gpt4v_custom_losses_20samples.json'
    # custom_losses_path: 'datasets/original/FlickrCI3D_Signatures/test/test_gpt4v_custom_losses_20samples.json'
    processed_pkl_extension: '_bev_optimization.pkl'
  chi3d:
    load_contact_frame_only: True
    load_single_camera: False
    custom_losses_path: 'datasets/original/CHI3D/train/trainval_gpt4v_prompt2_custom_losses.json'
    # custom_losses_path: 'datasets/original/CHI3D/test/test_gpt4v_prompt2_custom_losses.json'
  hi4d:
    load_single_camera: True
    custom_losses_path: 'datasets/original/Hi4D/val_gpt4v_prompt2_custom_losses.json'
    # custom_losses_path: 'datasets/original/Hi4D/test_gpt4v_prompt2_custom_losses.json'
  augmentation:
    use: False
  processing:
    use: False
model:
  optimization:
    type: 'hhcs'
    print_loss: False
    hhcs:
      max_iters: [1000, 1000]
      num_prev_steps: 20
      slope_tol: -0.0001
    optimizer: 
      type: 'adam'
      adam:
        lr: 0.01
    losses:
      keypoint2d: # 2d keypoint loss 
        type: 'l2'
        squared: True
        weighted: True
        weight: [0.04, 0.1]
      custom: # sum over minimum distance between regions in contact
        weight: [1000.0, 1000.0]
      hhc_contact_general: # contact loss that resolves intersection and brings part close to each other in contact. Memory intense.
        type: 'hhcgen'
        weight: [0.0, 1000.0] # must be set to 0.0, because loss is not implemented
      init_pose: # penalize deviation from inital bev pose
        type: 'l2'
        squared: True
        d1_aggregation: 'none'
        weight: [200.0, 200.0]
      pose_prior: # usual gmm pose prior
        type: 'gmm'
        weight: [4.0, 4.0]
      shape_prior: # usual shape prior
        type: 'l2'
        squared: True
        weight: [40.0, 0.0]
      ground_plane:
        type: 'l2'
        squared: True
        d1_aggregation: 'none'
        weight: [0.0, 0.0]
body_model:
  type: 'smplx'
  smplx:
    init:
      batch_size: 1
      gender: 'neutral'
      age: 'kid'
      joint_mapper:
        use: True
        type: 'smpl_to_openpose'
        smpl_to_openpose:
          use_hands: False
          use_face: False
          use_face_contour: False
camera:
  type: 'perspective'
  perspective:
    afov_horizontal: 60 # inital angular field of view compatible with bev output
    roll: 180 # inital camera roll compatible with bev output
